title: "Sans Souci"
author: "Yiran"
description: "Personal blog and website of Yiran"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

sidebar: false # show a sidebar instead of the usual header
show_excerpts: false # show article excerpts on the home page
show_related: true # show the previous and next links after every post
show_description: true # show the site description in the sidebar
show_title: false # always keep the site title visible

# Styling

dark_header: false # always keep the header dark
minimal: true # use simpler style

# # style: minimal             # use a simpler style inspired by the minima theme
# hide_title: false # remove site heading in the header
# hide_footer: false # hide the "previous" and "next" links at the end of each post
# dark_theme: false # use the dark mode as default
# dark_header: true # keep the header dark
# dark_footer: false # keep the footer dark

# Menu

navigation:
  - { file: "index.html", icon: home }
  - { file: "about.md", icon: address-card }

external: # see http://fontawesome.com/icons
 - {title: Mail, icon: envelope, url: "mailto:huangyr09@gmail.com"}
 - {title: Github, icon: github, url: "https://github.com/YiranH"}
 - {title: Subscribe, icon: rss, url: "/feed.xml"}

comments:
#  disqus_shortname: ""      # see https://disqus.com/
#  isso_domain: ""           # see https://posativ.org/isso/

plugins:
  - jekyll-feed
  - jekyll-default-layout
